[[rdma_core]]
arch = "aarch64"
git-tree-sha1 = "64d639cac0170a12235eb95cd01c3dfcc9332dc5"
libc = "glibc"
os = "linux"

    [[rdma_core.download]]
    sha256 = "174d0d92c1bdc069e3579c09d8b5d8438c211c65df76bdacc2eb5ae5748176d9"
    url = "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.aarch64-linux-gnu.tar.gz"
[[rdma_core]]
arch = "aarch64"
git-tree-sha1 = "ca742227830d583aae9c909d402d38eb5e1bcc01"
libc = "musl"
os = "linux"

    [[rdma_core.download]]
    sha256 = "e69c99c8fed8cef0eff27f94ed14dbd54a2fbdc9f56e18ccf02366f9d37ec55f"
    url = "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.aarch64-linux-musl.tar.gz"
[[rdma_core]]
arch = "i686"
git-tree-sha1 = "8cb94ea93478de590bac066421fbb621485e313f"
libc = "glibc"
os = "linux"

    [[rdma_core.download]]
    sha256 = "af691cb374bc9d72e819b5cd790c5f4f11bd8b401898142370c7e211175dcbbe"
    url = "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.i686-linux-gnu.tar.gz"
[[rdma_core]]
arch = "i686"
git-tree-sha1 = "1342d6c0d9937131cd131b159876914211f53fb2"
libc = "musl"
os = "linux"

    [[rdma_core.download]]
    sha256 = "74697f16104cc0964847816ab331a67deb3fb93762aa3fe7c64ace2006173da4"
    url = "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.i686-linux-musl.tar.gz"
[[rdma_core]]
arch = "powerpc64le"
git-tree-sha1 = "3ec4214665ff309f376f04803fbd270651094fc8"
libc = "glibc"
os = "linux"

    [[rdma_core.download]]
    sha256 = "7c8e944f10402f1c2a452ec0192e28b706f1c45de5cfc35365920cd19ee21d9d"
    url = "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.powerpc64le-linux-gnu.tar.gz"
[[rdma_core]]
arch = "x86_64"
git-tree-sha1 = "404b21a31d8b64fef8960ea1f4f6d1a2773799fc"
libc = "glibc"
os = "linux"

    [[rdma_core.download]]
    sha256 = "93d64080338c1be108e38fb7549fabd6734c2bee8290e15d8dd2683c991cb42c"
    url = "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.x86_64-linux-gnu.tar.gz"
[[rdma_core]]
arch = "x86_64"
git-tree-sha1 = "e384ee37163046c9b23b9396d5f3f9078dd0fe94"
libc = "musl"
os = "linux"

    [[rdma_core.download]]
    sha256 = "f96f2d3a66d87f7359951fa903f7b2f0a1e0e520626e75f2b1c7d9a581d4c341"
    url = "https://github.com/JuliaBinaryWrappers/rdma_core_jll.jl/releases/download/rdma_core-v58.0.0+0/rdma_core.v58.0.0.x86_64-linux-musl.tar.gz"
